# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
 
jobs:
  start-hardhat-node:
    runs-on: ubuntu-latest

#     strategy:
#       matrix:
#         node-version: [16.x]


    steps:
    - uses: actions/checkout@v3
      with:
        node-version: '16.x'
        registry-url: 'https://registry.npmjs.org'
    - run: yarn install
    - run: yarn coverage
        

#     - run: yarn compile
#     - run: yarn test
      
